### ISSUE TITLE
Record a list of accessed symbols

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide-pack#32]
I'm trying to record the list of symbols that are being accessed in a given Pyodide application at runtime. So what I would like to do is to record a list of all argument calls of [`pyodide._module.__dlsym_js`](https://github.com/emscripten-core/emscripten/blob/main/src/library_dylink.js#L1201) which then ends up being called in the real dlsym from C [here](https://github.com/emscripten-core/emscripten/blob/main/system/lib/libc/dynlink.c#L664) in Emscripten. Together with `pyodide._module.LDSO['loadedLibsByHandle']` that should tell which symbol is being loaded from which .so file.  The end goal is to not bundle .so which are not being accessed.

I have tried doing something like,
```js
  let dlsymCalls = [];  
  const dlsymOrig = pyodide._module.__dlsym_js;    
  pyodide._module.__dlsym_js = function(handle, symbol, symbolIndex) {
        dlsymCalls.push({handle: handle, symbol: symbol, symbolIndex: symbolIndex});       
        return dlsymOrig(handle, symbol, symbolIndex);                                      
  }
```
and then after `import scipy` I would expect some values in that list. But I get nothing.

Same by doing it via apply,
```js
  let dlsymCalls = [];  
  pyodide._module.__dlsym_js.apply = function(context, args) {
    dlsymCalls.push(args); 
    return this.original.apply(context, args); 
  };  
```

Do you see another way of doing this via monkeypatching without patching emscripten code?

 Maybe a question for @hoodmane since you were interested some time ago in Emscripten's dynamic linking code )

**Comment by hoodmane** [comment]
I think the following works but it isn't exactly pretty:
```js
let gottenSyms = new Set();
function wrapSym(symName, sym) {
  if (!sym) {
    return sym;
  }
  return new Proxy(sym, {
    get(sym, attr) {
      if (attr === "stub") {
        gottenSyms.add(symName);
      }
      return Reflect.get(sym, attr);
    },
  });
}

function wrapExports(exports) {
  if (typeof exports !== "object") {
    return exports;
  }
  return new Proxy(exports, {
    get(exports, symName) {
      const sym = Reflect.get(exports, symName);
      if (gottenSyms.has(symName)) {
        return sym;
      }
      return wrapSym(symName, sym);
    },
  });
}

function wrapLib(lib) {
  return new Proxy(lib, {
    get(lib, sym) {
      return wrapExports(Reflect.get(lib, sym));
    },
  });
}
origLoadedlibs = pyodide._module.LDSO.loadedLibsByName;
pyodide._module.LDSO.loadedLibsByName = new Proxy(origLoadedlibs, {
  set(libsByName, libName, lib) {
    return Reflect.set(libsByName, libName, wrapLib(lib));
  },
});
```

**Comment by rth** [comment]
Thank's @hoodmane this works, but indeed not that direct.
