### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide-pack#6]
As a name "pyodide-pack" works but is a bit boring, and it would be even worse if we start using subcommand (e.g. `pyodide-pack minimize`). Instead, it would be better to give it a shorter and nicer name,

Some (not very good) ideas,
 - pyopack: might be confusing with https://github.com/seemoo-lab/openwifipass/blob/main/OPACK.md already
 - pypack: maybe too general and the package already exists
 - wpack: (with ''w' for web and wasm) a bit difficult to read, and also feels like a name stealing from webpack
 - ypack: ("yp" -> "py")  maybe, but the link with wasm is not obvious, name registered on pypi but could probably be released
 - wapack: (wa as webassembly) maybe, but then it would have been preferrable to have a Python reference
 - yopack (from p*yo*dide) doesn't sound very serious

If you have any other ideas please comment

**Comment by ricardoprins** [comment]
What about pyodide-slim?

**Comment by ricardoprins** [comment]
That makes sense. 

What about 'reducio'? Harry Potter's shrinking charm spell haha

**Comment by rth** [comment]
Thanks for the suggestions. 

6 month later, I think we can just keep the name. CLI wise we will be able to register it as `pyodide pack` which is good enough I think. Closing as resolved.
